/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Games */
        get: operations["list_games_api_v1_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game */
        get: operations["get_game_api_v1_games__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/covers/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cover */
        get: operations["get_cover_api_v1_media_covers__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Monitor */
        get: operations["get_monitor_api_v1_monitor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/monitor/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Monitor */
        get: operations["stream_monitor_api_v1_monitor_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Platforms */
        get: operations["list_platforms_api_v1_platforms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Run */
        post: operations["start_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** GameCardRead */
        GameCardRead: {
            /** Cover Url */
            cover_url?: string | null;
            critic?: components["schemas"]["ReviewSummary"] | null;
            /** Description */
            description?: string | null;
            /** Developer */
            developer?: string | null;
            /** Genres */
            genres?: string[];
            letsplay?: components["schemas"]["LetsPlayRead"] | null;
            /** Metacritic Slug */
            metacritic_slug: string;
            /** Platforms */
            platforms?: components["schemas"]["PlatformScore"][];
            /** Publisher */
            publisher?: string | null;
            /** Release Date */
            release_date?: string | null;
            /** Similar */
            similar?: components["schemas"]["SimilarGameRef"][];
            /** Title */
            title: string;
            user?: components["schemas"]["ReviewSummary"] | null;
            /** Video Url */
            video_url?: string | null;
        };
        /** GameListItemRead */
        GameListItemRead: {
            /** Cover Url */
            cover_url?: string | null;
            /** Developer */
            developer?: string | null;
            /** Metacritic Slug */
            metacritic_slug: string;
            /** Metascore */
            metascore?: number | null;
            /** Platforms */
            platforms?: string[];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Userscore */
            userscore?: number | null;
        };
        /** GameListResponse */
        GameListResponse: {
            /** Items */
            items: components["schemas"]["GameListItemRead"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LetsPlayRead */
        LetsPlayRead: {
            /** Conclusion */
            conclusion?: string | null;
            /** Highlights */
            highlights?: string[] | null;
            /** Status */
            status?: ("ok" | "no_video" | "transcript_unavailable" | "quota_exceeded") | null;
            /** Video Title */
            video_title?: string | null;
            /** Video Url */
            video_url?: string | null;
            /** View Count */
            view_count?: number | null;
        };
        /** LivenessResponse */
        LivenessResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** MonitorCursorRead */
        MonitorCursorRead: {
            /** Last Browse Page */
            last_browse_page?: number | null;
            /** New Releases Done */
            new_releases_done: boolean;
            /**
             * Process Date
             * Format: date
             */
            process_date: string;
        };
        /** MonitorItemRead */
        MonitorItemRead: {
            /** Error Message */
            error_message?: string | null;
            /** Error Type */
            error_type?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metacritic Slug */
            metacritic_slug: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "discovered" | "cataloged" | "reviews" | "letsplay" | "similar";
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed" | "degraded";
            /** Title */
            title?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MonitorRunRead */
        MonitorRunRead: {
            /** Completed At */
            completed_at?: string | null;
            /** Discovered Count */
            discovered_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Limit */
            limit: number;
            /** Page */
            page?: number | null;
            /**
             * Process Date
             * Format: date
             */
            process_date: string;
            /** Source */
            source: string;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "requested" | "running" | "completed" | "failed";
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "cron" | "manual";
        };
        /** MonitorScrapeRead */
        MonitorScrapeRead: {
            /** Circuit State */
            circuit_state?: ("closed" | "open" | "half_open") | null;
            /** Last Parse Error At */
            last_parse_error_at?: string | null;
            /** Parse Error Count */
            parse_error_count: number;
        };
        /** MonitorSnapshot */
        MonitorSnapshot: {
            /** Counts */
            counts: components["schemas"]["StageStatusCountRead"][];
            cursor?: components["schemas"]["MonitorCursorRead"] | null;
            /** Items */
            items: components["schemas"]["MonitorItemRead"][];
            /**
             * Process Date
             * Format: date
             */
            process_date: string;
            /** Runs */
            runs: components["schemas"]["MonitorRunRead"][];
            scrape: components["schemas"]["MonitorScrapeRead"];
            /** Workers */
            workers: components["schemas"]["WorkerHeartbeatRead"][];
        };
        /** PaginationMeta */
        PaginationMeta: {
            /**
             * Order
             * @enum {string}
             */
            order: "asc" | "desc";
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /**
             * Sort
             * @enum {string}
             */
            sort: "metascore" | "userscore" | "title" | "updated";
            /** Total */
            total: number;
        };
        /** PlatformListResponse */
        PlatformListResponse: {
            /** Items */
            items: string[];
        };
        /** PlatformScore */
        PlatformScore: {
            /** Metascore */
            metascore?: number | null;
            /** Platform Code */
            platform_code: string;
            /** Userscore */
            userscore?: number | null;
        };
        /** ProblemDetails */
        ProblemDetails: {
            /** Detail */
            detail?: string | null;
            /** Instance */
            instance?: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Kafka */
            kafka?: boolean | null;
            /** Postgres */
            postgres: boolean;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** ReviewSummary */
        ReviewSummary: {
            /** Dislikes */
            dislikes: string[];
            /** Likes */
            likes: string[];
            /** Summary */
            summary: string;
        };
        /** RunAcceptedResponse */
        RunAcceptedResponse: {
            /**
             * Process Date
             * Format: date
             */
            process_date: string;
            /**
             * Status
             * @default run_accepted
             * @constant
             */
            status: "run_accepted";
        };
        /** SimilarGameRef */
        SimilarGameRef: {
            /** Metacritic Slug */
            metacritic_slug: string;
            /** Rank */
            rank: number;
            /** Score */
            score: number;
            /** Title */
            title: string;
        };
        /** StageStatusCountRead */
        StageStatusCountRead: {
            /** Count */
            count: number;
            /** Stage */
            stage: string;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkerHeartbeatRead */
        WorkerHeartbeatRead: {
            /** Current Subject */
            current_subject?: string | null;
            /** Instance Id */
            instance_id: string;
            /** Lag Hint */
            lag_hint?: number | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Processed Failed */
            processed_failed: number;
            /** Processed Ok */
            processed_ok: number;
            /** Stale */
            stale: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "idle" | "running" | "error";
            /** Worker Type */
            worker_type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_games_api_v1_games_get: {
        parameters: {
            query?: {
                q?: string | null;
                platform?: string | null;
                sort?: "metascore" | "userscore" | "title" | "updated";
                order?: "asc" | "desc";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameListResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_game_api_v1_games__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameCardRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_cover_api_v1_media_covers__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "image/jpeg": unknown;
                    "image/png": unknown;
                    "image/webp": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Cover file is missing */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_monitor_api_v1_monitor_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorSnapshot"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    stream_monitor_api_v1_monitor_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE кадры снимка монитора */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    list_platforms_api_v1_platforms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformListResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    start_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAcceptedResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
